import {
  EMAIL,
  EMAIL_FA,
  EMAIL_SAMPLE,
  LASTNAME,
  LASTNAME_FA,
  NAME,
  NAME_FA,
  NUMBER,
  PASSWORD,
  PASSWORD_FA,
  PASSWORD_SAMPLE,
  PHONE,
  PHONE_NUMBER_FA,
  TEXT,
  USERNAME,
  USERNAME_FA,
} from "../../../../constant/messages";

export const formStructure = [
  {
    id: 1,
    size: 12,
    type: TEXT,
    placeholder: NAME_FA,
    name: NAME,
    label: NAME,
    validation: {
      required: true,
      maxLength: 220,
      minLength: 2,
    },
  },
  {
    id: 2,
    size: 12,
    type: TEXT,
    placeholder: LASTNAME_FA,
    name: LASTNAME,
    label: LASTNAME_FA,
    validation: {
      required: true,
      maxLength: 220,
      minLength: 2,
    },
  },
  {
    id: 3,
    size: 12,
    type: TEXT,
    placeholder: USERNAME_FA,
    name: USERNAME,
    label: USERNAME_FA,
    validation: {
      required: true,
      maxLength: 220,
      minLength: 2,
    },
  },
  {
    id: 4,
    size: 12,
    type: TEXT,
    placeholder: EMAIL_SAMPLE,
    name: EMAIL,
    label: EMAIL_FA,
    validation: {
      required: true,
      maxLength: 220,
      minLength: 2,
    },
  },
  {
    id: 5,
    size: 12,
    type: NUMBER,
    placeholder: PHONE_NUMBER_FA,
    name: PHONE,
    label: PHONE_NUMBER_FA,
    validation: {
      required: true,
      maxLength: 220,
      minLength: 2,
    },
  },
  {
    id: 6,
    size: 12,
    type: PASSWORD,
    placeholder: PASSWORD_SAMPLE,
    name: PASSWORD,
    label: PASSWORD_FA,
    validation: {
      required: true,
      maxLength: 20,
      minLength: 5,
    },
  },
];
