import {
  EDUCATION_EXPERIENCE_INFO_FA,
  EDUCATION_EXPERIENCE_DESC_FA,
  EDUCATION_FEILD_SAMPLE_FA,
  EDUCATION_EXPERIENCE_DESC,
  EDUCATION_DATE_SAMPLE_FA,
  START_EDUCATION_DATE_FA,
  END_EDUCATION_DATE_FA,
  UNIVERSITY_SAMPLE_FA,
  START_EDUCATION_DATE,
  END_EDUCATION_DATE,
  EDUCATION_FEILD_FA,
  EDUCATION_LEVEL_FA,
  KARSHENASI_ARSHAD,
  STILL_STUDENT_FA,
  EDUCATION_FEILD,
  UNIVERSITY_FA,
  STIll_STUDENT,
  DOCTORA_MORE,
  KARSHENASI,
  UNIVERSITY,
  CHECKBOX,
  TEXTAREA,
  KARDANI,
  DIPLOM,
  NUMBER,
  RADIO,
  TEXT,
} from "../../../../../../constant/messages";

export const formStructure = (stillEducating) => {
  let form = {
    education: {
      title: EDUCATION_EXPERIENCE_INFO_FA,
      form: [
        {
          id: 1,
          size: 6,
          type: TEXT,
          name: EDUCATION_FEILD,
          placeholder: EDUCATION_FEILD_SAMPLE_FA,
          label: EDUCATION_FEILD_FA,
          labelRequired: true,
          validation: {
            required: true,
            minLength: 1,
            maxLength: 250,
          },
        },
        {
          id: 2,
          size: 6,
          type: TEXT,
          name: UNIVERSITY,
          placeholder: UNIVERSITY_SAMPLE_FA,
          label: UNIVERSITY_FA,
          labelRequired: true,
          validation: {
            required: true,
            minLength: 1,
            maxLength: 250,
          },
        },
        {
          id: 3,
          size: 12,
          inline: true,
          type: RADIO,
          name: "education_level",
          label: EDUCATION_LEVEL_FA,
          labelRequired: true,
          data: [
            { id: 1, label: DIPLOM, value: DIPLOM },
            { id: 2, label: KARDANI, value: KARDANI },
            { id: 3, label: KARSHENASI, value: KARSHENASI },
            { id: 4, label: KARSHENASI_ARSHAD, value: KARSHENASI_ARSHAD },
            { id: 5, label: DOCTORA_MORE, value: DOCTORA_MORE },
          ],
          validation: {
            required: true,
          },
        },
        {
          id: 4,
          size: !stillEducating ? 6 : 12,
          type: NUMBER,
          name: START_EDUCATION_DATE,
          placeholder: EDUCATION_DATE_SAMPLE_FA,
          label: START_EDUCATION_DATE_FA,
          labelRequired: true,
          validation: {
            required: true,
            minLength: 3,
            maxLength: 5,
          },
        },
        !stillEducating && {
          id: 5,
          size: 6,
          type: NUMBER,
          name: END_EDUCATION_DATE,
          placeholder: EDUCATION_DATE_SAMPLE_FA,
          label: END_EDUCATION_DATE_FA,
          labelRequired: true,
          validation: {
            required: true,
            minLength: 3,
            maxLength: 5,
          },
        },
        {
          id: 6,
          size: 12,
          type: CHECKBOX,
          name: STIll_STUDENT,
          label: "",
          labelRequired: "",
          data: [
            {
              id: 1,
              inputId: 1,
              name: STIll_STUDENT,
              label: STILL_STUDENT_FA,
            },
          ],
          validation: { required: false },
        },
        {
          id: 7,
          size: 12,
          inline: true,
          type: TEXTAREA,
          labelRequired: false,
          name: EDUCATION_EXPERIENCE_DESC,
          placeholder: "",
          label: EDUCATION_EXPERIENCE_DESC_FA,
          rows: 5,
          validation: {
            required: false,
          },
        },
      ],
    },
  };

  return form;
};
