export const formStructure = {
  employementType: {
    id: 1,
    size: 12,
    type: "checkbox",
    name: "employementType",
    label: "",
    labelRequired: "",
    data: [
      {
        id: 1,
        inputId: 1,
        name: "تمام وقت",
        value: "تمام وقت",
        label: "تمام وقت",
        amount: "1335",
      },
      {
        id: 2,
        inputId: 2,
        value: "پاره وقت",
        name: "پاره وقت",
        label: "پاره وقت",
        amount: "250",
      },
      {
        id: 3,
        inputId: 3,
        value: "دورکاری",
        name: "دورکاری",
        label: "دورکاری",
        amount: "110",
      },
    ],
  },
  level: {
    id: 2,
    size: 12,
    type: "checkbox",
    name: "workSurface",
    label: "",
    labelRequired: "",
    data: [
      {
        id: 4,
        inputId: 4,
        name: "Senior",
        label: "Senior",
        amount: "1400",
      },
      { id: 5, inputId: 5, name: "Junior", label: "Junior", amount: "250" },
      { id: 6, inputId: 6, name: "کارآموز", label: "کارآموز", amount: "110" },
    ],
  },
  salary: {
    id: 3,
    size: 12,
    type: "salary",
    name: "salary",
    label: "",
    labelRequired: "",
    data: [
      {
        id: 7,
        inputId: 7,
        name: "از ۳٫۰۰۰٫۰۰۰",
        label: "از ۳٫۰۰۰٫۰۰۰",
        amount: "320",
      },
      {
        id: 8,
        inputId: 8,
        name: "از ۳٫۰۰۰٫۰۰۰ تا ۸٫۰۰۰٫۰۰۰",
        label: "از ۳٫۰۰۰٫۰۰۰ تا ۸٫۰۰۰٫۰۰۰",
        amount: "250",
      },
      {
        id: 9,
        inputId: 9,
        name: "از ۸٫۰۰۰٫۰۰۰ تا ۱۵٫۰۰۰٫۰۰۰",
        label: "از ۸٫۰۰۰٫۰۰۰ تا ۱۵٫۰۰۰٫۰۰۰",
        amount: "110",
      },
      {
        id: 10,
        inputId: 10,
        name: "از ۸٫۰۰۰٫۰۰۰ تا ۱۵٫۰۰۰٫۰۰۰",
        label: "از ۱۵٫۰۰۰٫۰۰۰ تا ۲۰٫۰۰۰٫۰۰۰",
        amount: "110",
      },
      {
        id: 11,
        inputId: 11,
        name: "از  ۲۰٫۰۰۰٫۰۰۰",
        label: "از  ۲۰٫۰۰۰٫۰۰۰",
        amount: "110",
      },
    ],
  },
};
