import {
  TEXT,
  NAME,
  LASTNAME,
  MAHDI,
  ALIPOUR,
  NAME_FA,
  LASTNAME_FA,
  EMAIL,
  EMAIL_FA,
  EMAIL_SAMPLE,
  NUMBER,
  PHONE_NUMBER,
  PHONE_NUMBER_SAMPLE,
  PHONE_NUMBER_FA,
  PERSONAL_DATAS,
  RADIO,
  MARIEGDE_STATUS,
  MARIEDGE_STATUS_FA,
  SINGLE,
  COUPLE,
  SEX_FA,
  SEX,
  MALE,
  FEMAIL,
  TEXTAREA,
  WRITE_ABOUT_YOURSELF,
  ABOUT_USER_FA,
  ABOUT_USER,
} from "../../../../constant/messages";

export const formStructure = {
  personalDataForm: {
    title: PERSONAL_DATAS,
    form: [
      {
        id: 1,
        size: 6,
        type: TEXT,
        name: NAME,
        placeholder: MAHDI,
        label: NAME_FA,
        labelRequired: true,
        validation: {
          required: true,
          minLength: 1,
          maxLength: 250,
        },
      },
      {
        id: 2,
        size: 6,
        type: TEXT,
        name: LASTNAME,
        placeholder: ALIPOUR,
        label: LASTNAME_FA,
        labelRequired: true,
        validation: {
          required: true,
          minLength: 1,
          maxLength: 250,
        },
      },
      {
        id: 3,
        size: 6,
        type: EMAIL,
        name: EMAIL,
        placeholder: EMAIL_SAMPLE,
        label: EMAIL_FA,
        labelRequired: true,
        disabled: true,
        validation: {
          required: true,
          minLength: 1,
          maxLength: 250,
        },
      },
      {
        id: 4,
        size: 6,
        type: NUMBER,
        name: PHONE_NUMBER,
        placeholder: PHONE_NUMBER_SAMPLE,
        label: PHONE_NUMBER_FA,
        labelRequired: true,
        validation: {
          required: true,
          minLength: 10,
          maxLength: 12,
        },
      },
      {
        id: 5,
        size: 6,
        inline: true,
        type: RADIO,
        name: MARIEGDE_STATUS,
        label: MARIEDGE_STATUS_FA,
        labelRequired: true,
        data: [
          { id: 1, label: SINGLE, value: SINGLE },
          { id: 2, label: COUPLE, value: COUPLE },
        ],
        validation: {
          required: true,
        },
      },
      {
        id: 6,
        size: 6,
        inline: true,
        type: RADIO,
        name: SEX,
        label: SEX_FA,
        labelRequired: true,
        data: [
          { id: 1, label: MALE, value: MALE },
          { id: 2, label: FEMAIL, value: FEMAIL },
        ],
        validation: {
          required: true,
        },
      },
      {
        id: 7,
        size: 12,
        inline: true,
        type: TEXTAREA,
        labelRequired: true,
        name: ABOUT_USER,
        placeholder: WRITE_ABOUT_YOURSELF,
        label: ABOUT_USER_FA,
        rows: 5,
        validation: {
          required: true,
          minLength: 10,
          maxLength: 300,
        },
      },
    ],
  },
};
